### ISSUE TITLE
Definir Formato

### ISSUE THREAD

**Issue by lbighetti** [training-center/remote-meetup#2]
Pessoal, muitos meetups ao redor do mundo o formato é 3x talks de 30 minutos.

Porém, na issue https://github.com/training-center/forum/issues/59 levantaram um ponto excelente:  atenção das pessoas online é *MUITO* menor que ao vivo. 

Por exemplo, a média de tempo que um usuário assiste um vídeo no YouTube é de 5 a 7 minutos.

@woliveiras sugeriu 18 minutos de talk e 7 de perguntas.
O que daria 65 minutos no total pro evento.
Intro + outro, 70 miuntos digamos, 1h10.

O que acham ?

**Comment by mstuttgart** [comment]
A susgestão que daria seria diminuir de 18 para 15 minutos para ficar um valor mais "fechado". No mais, ótima iniciativa :+1:

**Comment by lbighetti** [comment]
boa @mstuttgart 👍 

alternativamente a gente podia fazer um talk maior e dois menores.
não sei se funcionaria melhor ou pior.

podiamos talvez tentar e ver o feedback ?

**Comment by lbighetti** [comment]
outra coisa -  questão de schedule, pensei em fazer todo 3o domingo do mês.
daí fica com uma frequência fixa e o pessoal começa se planejar com o tempo! 💪 
o que acham ?

**Comment by rafaels88** [comment]
> alternativamente a gente podia fazer um talk maior e dois menores

Vamos tentar! Se não der a gente faz diferente no próximo! 
- 5 minutos introdução e boas vindas'
- 2 talks de 15 minutos + 5 minutos de PR pra cada
- 1 talk de 20 minutos + 5 minutos de PR
= 70 minutos

É isso?

> questão de schedule, pensei em fazer todo 3o domingo do mês.

Vamos tentar tbm. Se começarmos a ter problema por falta de público ou talks a gt faz a cada 60 dias, de repente.

Tenho uma questão, podíamos já definir a ferramenta a ser usada. Muita gente não gosta de certa ferramenta, ou prefere outra, isso sempre gera uma discussão leve mas importante.

Eu gosto muito do Slack mas não tenho certeza se dá pra fazer call com vídeo na versão gratuita; Gosto do appear.in tbm, ele só é muito pesado pra celular, não sei se alguém assistiria pelo celular o meeting; E no mais tem o bom e velho Skype :p 

Alguém tem outros candidatos?

**Comment by lbighetti** [comment]
> Vamos tentar! Se não der a gente faz diferente no próximo!

Boa!

>5 minutos introdução e boas vindas'
>2 talks de 15 minutos + 5 minutos de PR pra cada
>1 talk de 20 minutos + 5 minutos de PR
>= 70 minutos

Então pensei em algo mais brusco heehhe
tipo 1x Talk de 20-30min "principal", e tipo 2-3x _lightning talks_: talks de 5-10 minutos.

Isso é algo que as vezes no meetup de elixir Berlin fazemos e dá bem certo, depois de um talk grande tipo sua paciência já foi um pouco pro saco, aí talks menores caem bem. heheheh 

Acho que pode ser uma idéia a se explorar também.

Por exemplo, esse Ted Talk incrível, que o Speaker fala de um temo extremamente complexo em ~7 minutos.  
https://www.youtube.com/watch?v=wOsQKjNoHmw

Mas acho que é difícil definir nesse primeiro.
Pra esse primeiro #1, bora fazer bem simples ? 3x 20 min + perguntas pra simplificar ?

Dai pegamos o feedback tanto dos speakers como de quem tá assistindo!
Acho que tem algumas coisas que podem surgir como:
Foi legal todos, foi bom o primeiro mas depois ficou maçante, foram todos muito longos, todos muito curtos.
Eu pessoalmente to perdido, não sei qual vai ser o feeling 🤣  ehhee

> Se começarmos a ter problema por falta de público ou talks a gt faz a cada 60 dias, de repente.

Fechado ! 👍 

> Eu gosto muito do Slack mas não tenho certeza se dá pra fazer call com vídeo na versão gratuita; >Gosto do appear.in tbm, ele só é muito pesado pra celular, não sei se alguém assistiria pelo celular o >meeting; E no mais tem o bom e velho Skype :p
>Alguém tem outros candidatos?

Eu pensei em Hangouts + YouTube
Esse setup é super simples de fazer e funciona bem no geral.

Streaming do YouTube é monstruoso, é foda de bater a qualidade.
Essas ferramentas de conferências passou de umas 20 pessoas todas começam a capotar na minha experiência.  
Outro benefício é que no Hangouts + YouTube o YT já grava pra vc e posta no canal automático, pra quem vier depois quiser assistir 💪

**Comment by alinebastos** [comment]
Eu já acho o ideal 3 talks de 15 minutos.
Não fica muito longo.
Fica mais fácil qualquer pessoa se candidatar pra fazer uma talk.
Não fica uma sendo a "mais importante", todas são iguais.
Nunca gostei de eventos e meetups que tem uma talk mais longa que as outras.
Gosto que todos sejam iguais.

**Comment by alinebastos** [comment]
Acho que me repeti bastante ali em cima, haha.

**Comment by lbighetti** [comment]
@alinebastos bom ponto 👍 
Daí não precisamos `decidir` também qual talk é o maior.  
A gente pode talvez só deixar de opção se alguém quiser, ou se no dia algum speaker der pra trás, abrir pra lightning talks como alternativa.

> Não fica muito longo.
Não fica muito longo, eu to com medo é de ficar muito curto 😛. Mas talvez pra internet seja melhor pecar pra muito curto do que pra muito longo mesmo, porque é muito fácil de perder a atenção das pessoas.

Eu topo esse formato! Fica simples e rápido. 3x talks de 15 minutos.
3x 15 + 5 min perguntas da 1h certinho + introdução/finalização digamos, 1h10

**Comment by rafaels88** [comment]
Curti muito tbm, ótimos pontos @alinebastos!

> Eu pensei em Hangouts + YouTube
Esse setup é super simples de fazer e funciona bem no geral.

Mas como vai funcionar na prática isso, exatamente? Cada pessoa vai estar em um lugar diferente. Se for pra filmar a pessoa falando, vamos ter q parar o streaming e iniciar um novo toda vez, seria isso? E quando você fala Hangouts, é aquele chat no próprio Youtube mesmo?

**Comment by lbighetti** [comment]
O Hangouts é tipo o Skype do Google mano, se pans tu nunca usou pelo que tá falando.

Ele tem detecção automática de quem tá falando fica na tela. Já é integrado com o YouTube e você consegue fazer stream direto pro YouTube da sessão de chat.

E nesse caso tem o `admin` da sessão pode forçar a camera de alguém ficar ativa, que provavelmente é o que faremos!

Aqui por exemplo, eles tão todos conversando por esse app fazendo stream pro YouTube (eles só estão áudio nesse caso, mas dá pra entender a idéia) ->https://www.youtube.com/watch?v=J5Wjtrp0WV0

Dai pensei em fazer esse Hangouts só entre os speakers e o host, fazendo stream pro YouTube.
E lá no youtube quando você tá ao vivo tem aquele chat que funciona super bem, ai quem tá assistindo pode se comunicar por lá, fazer perguntas e tal.

Outro exemplo que fiz também com esse setup: Dá pra mudar da camera pra sua tela também bem suave. Esse eu fui lendo as perguntas e respondendo por esse chat ->
https://www.youtube.com/watch?v=sReZI1izRZI

Claro, acho que tem maneiras mais _profissionais_ de fazer, mas acho que esse é um bom meio termo de qualidade/esforço.

**Comment by rafaels88** [comment]
Haa po, boa! Já usei sim mas não sabia sobre essa integração Hangouts + Youtube hahaha pra mim eles caminhavam separado apesar de serem do Google. Pensando agora, foi bem idiota da minha parte, já assisti alguns streamings no Youtube com a galera no hangouts hahaha Vlw pela explicação!

Fechado então!

**Comment by lbighetti** [comment]
Boa, 3x 15 minutos + 5 perguntas, Hangouts e YouTube então!

Vou por no README!
Vamos pegar feedback nesse primeiro meetup e ai pensamos como melhorar pro próximo :)

Valeu todo mundo 👍 💪
